### ISSUE TITLE
Przykłady użycia

### ISSUE THREAD

**Issue by Lebioda** [imper86/php-inpost-api#1]
Cześć,
czy można prosić o dodanie przykładów użycia, np. jak wygenerować i pobrać etykietę?

**Comment by imper86** [comment]
Hej,
Dodałem przykładowy skrypt - https://github.com/imper86/php-inpost-api/blob/master/examples/create_shipment.php
Daj znać czy wystarczy :)

**Comment by Lebioda** [comment]
Działa wyśmienicie, pięknie dziękuję :+1:
